# TCL File Generated by Component Editor 9.1sp1
# Thu Sep 09 13:02:32 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | uart_avalon_sopc "uart_avalon_sopc" v1.0
# | roger.yu 2010.09.09.13:02:32
# | uart core
# | 
# | E:/reway/25_UART-core/uart_avalon_sopc/hdl/uart_top.v
# | 
# |    ./hdl/uart_top.v syn, sim
# |    ./hdl/raminfr.v syn, sim
# |    ./hdl/timescale.v syn, sim
# |    ./hdl/uart_al.v syn, sim
# |    ./hdl/uart_debug_if.v syn, sim
# |    ./hdl/uart_defines.v syn, sim
# |    ./hdl/uart_receiver.v syn, sim
# |    ./hdl/uart_regs.v syn, sim
# |    ./hdl/uart_rfifo.v syn, sim
# |    ./hdl/uart_sync_flops.v syn, sim
# |    ./hdl/uart_tfifo.v syn, sim
# |    ./hdl/uart_transmitter.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module uart_avalon_sopc
# | 
set_module_property DESCRIPTION "uart core"
set_module_property NAME uart_avalon_sopc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP mycent
set_module_property AUTHOR roger.yu
set_module_property DISPLAY_NAME uart_avalon_sopc
set_module_property DATASHEET_URL http://www.icpc.cn
set_module_property TOP_LEVEL_HDL_FILE hdl/uart_top.v
set_module_property TOP_LEVEL_HDL_MODULE uart_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/uart_top.v {SYNTHESIS SIMULATION}
add_file hdl/raminfr.v {SYNTHESIS SIMULATION}
add_file hdl/timescale.v {SYNTHESIS SIMULATION}
add_file hdl/uart_al.v {SYNTHESIS SIMULATION}
add_file hdl/uart_debug_if.v {SYNTHESIS SIMULATION}
add_file hdl/uart_defines.v {SYNTHESIS SIMULATION}
add_file hdl/uart_receiver.v {SYNTHESIS SIMULATION}
add_file hdl/uart_regs.v {SYNTHESIS SIMULATION}
add_file hdl/uart_rfifo.v {SYNTHESIS SIMULATION}
add_file hdl/uart_sync_flops.v {SYNTHESIS SIMULATION}
add_file hdl/uart_tfifo.v {SYNTHESIS SIMULATION}
add_file hdl/uart_transmitter.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter uart_data_width INTEGER 32 ""
set_parameter_property uart_data_width DEFAULT_VALUE 32
set_parameter_property uart_data_width DISPLAY_NAME uart_data_width
set_parameter_property uart_data_width ENABLED false
set_parameter_property uart_data_width UNITS None
set_parameter_property uart_data_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property uart_data_width DESCRIPTION ""
set_parameter_property uart_data_width DISPLAY_HINT ""
set_parameter_property uart_data_width AFFECTS_GENERATION false
set_parameter_property uart_data_width HDL_PARAMETER true
add_parameter uart_addr_width INTEGER 5 ""
set_parameter_property uart_addr_width DEFAULT_VALUE 5
set_parameter_property uart_addr_width DISPLAY_NAME uart_addr_width
set_parameter_property uart_addr_width ENABLED false
set_parameter_property uart_addr_width UNITS None
set_parameter_property uart_addr_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property uart_addr_width DESCRIPTION ""
set_parameter_property uart_addr_width DISPLAY_HINT ""
set_parameter_property uart_addr_width AFFECTS_GENERATION false
set_parameter_property uart_addr_width HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset reset reset Input 1
add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 associatedClock clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 2
set_interface_property s1 readWaitTime 2
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitStates 1
set_interface_property s1 writeWaitTime 1

set_interface_property s1 ASSOCIATED_CLOCK clock_reset
set_interface_property s1 ENABLED true

add_interface_port s1 al_read_i read Input 1
add_interface_port s1 al_write_i write Input 1
add_interface_port s1 al_readdata_o readdata Output 32
add_interface_port s1 al_writedata_i writedata Input 32
add_interface_port s1 al_address_i address Input 5
add_interface_port s1 al_byteenable_i byteenable Input 4
add_interface_port s1 al_chipselect_i chipselect Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point int
# | 
add_interface int interrupt end
set_interface_property int associatedAddressablePoint s1

set_interface_property int ASSOCIATED_CLOCK clock_reset
set_interface_property int ENABLED true

add_interface_port int int_o irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point export
# | 
add_interface export conduit end

set_interface_property export ASSOCIATED_CLOCK clock_reset
set_interface_property export ENABLED true

add_interface_port export stx_pad_o export Output 1
add_interface_port export srx_pad_i export Input 1
add_interface_port export rts_pad_o export Output 1
add_interface_port export cts_pad_i export Input 1
add_interface_port export dtr_pad_o export Output 1
add_interface_port export dsr_pad_i export Input 1
add_interface_port export ri_pad_i export Input 1
add_interface_port export dcd_pad_i export Input 1
# | 
# +-----------------------------------
